spring.application.name=PhotoAppApiZuulAPIGateway
server.port=8011
eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka
#zuul.prefix=/api
#zuul.routes.users-route.path=/usersapi/
#zuul.routes.users-route.service-id=PHOTOAPPUSERS
#zuul.routes.account-route.path=/accountsapi/
#zuul.routes.account-route.service-id=PHOTOAPPACCOUNTMANAGEMENT


api.login.url.path=/users/login
api.registration.url.path=/users
h2.console.url.path=/h2-console
authorization.token.header.name=Authorization
authorization.token.header.prefix=Bearer
#token.secret=dbskbsdfASBFKJBDFSBFSAVJVDAFVBJDVYAWCRIYkdskjsbagihawigrhjkgskfhsjkgsag

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest