spring.application.name=PhotoAppApiSpringCloudAPIGateway
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
api.login.url.path=/users/login
api.registration.url.path=/users
h2.console.url.path=/h2-console
#request sent to microservice using application name
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
#token.secret=dbskbsdfASBFKJBDFSBFSAVJVDAFVBJDVYAWCRIYkdskjsbagihawigrhjkgskfhsjkgsag

spring.cloud.gateway.server.webflux.routes[0].id=users-status-check
spring.cloud.gateway.server.webflux.routes[0].uri=lb://photoappusers
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/status/check
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/photoappusers/users/status/check
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=GET
spring.cloud.gateway.server.webflux.routes[0].predicates[2]=Header=Authorization, Bearer (.*)
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[0].filters[1]=RewritePath=/photoappusers/(?<segment>.*), /$\{segment}
spring.cloud.gateway.server.webflux.routes[0].filters[2]=AuthorizationHeader


spring.cloud.gateway.server.webflux.routes[1].id=users-create
spring.cloud.gateway.server.webflux.routes[1].uri=lb://photoappusers
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/photoappusers/users
spring.cloud.gateway.server.webflux.routes[1].predicates[1]=Method=POST
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[1].filters[1]=RewritePath=/photoappusers/(?<segment>.*), /$\{segment}

spring.cloud.gateway.server.webflux.routes[2].id=h2-console
spring.cloud.gateway.server.webflux.routes[2].uri=lb://photoappusers
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/photoappusers/h2-console
spring.cloud.gateway.server.webflux.routes[2].predicates[1]=Method=GET
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[2].filters[1]=RewritePath=/photoappusers/(?<segment>.*), /$\{segment}


spring.cloud.gateway.server.webflux.routes[3].id=users-login
spring.cloud.gateway.server.webflux.routes[3].uri=lb://photoappusers
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/photoappusers/users/login
spring.cloud.gateway.server.webflux.routes[3].predicates[1]=Method=POST
spring.cloud.gateway.server.webflux.routes[3].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[3].filters[1]=RewritePath=/photoappusers/(?<segment>.*), /$\{segment}

spring.cloud.gateway.server.webflux.routes[4].id=users-ws-get-update-delete
spring.cloud.gateway.server.webflux.routes[4].uri=lb://photoappusers
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/photoappusers/users/**
spring.cloud.gateway.server.webflux.routes[4].predicates[1]=Method=GET,PUT,DELETE
spring.cloud.gateway.server.webflux.routes[4].predicates[2]=Header=Authorization, Bearer (.*)
spring.cloud.gateway.server.webflux.routes[4].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[4].filters[1]=AuthorizationHeader
spring.cloud.gateway.server.webflux.routes[4].filters[2]=RewritePath=/photoappusers/(?<segment>.*), /$\{segment}

spring.cloud.gateway.server.webflux.routes[5].id=users-ws-actuator
spring.cloud.gateway.server.webflux.routes[5].uri=lb://photoappusers
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/photoappusers/actuator/**
spring.cloud.gateway.server.webflux.routes[5].predicates[1]=Method=GET
spring.cloud.gateway.server.webflux.routes[5].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.server.webflux.routes[5].filters[1]=RewritePath=/photoappusers/(?<segment>.*), /$\{segment}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#spring.rabbitmq.virtual-host=/
#spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.bindQueue=true
#spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.declareExchange=true
#spring.cloud.stream.rabbit.bindings.springCloudBusInput.consumer.queueNameGroupOnly=false
spring.cloud.stream.bindings.springCloudBusInput.group=bus-group
spring.config.import=optional:configserver:http://localhost:8012
spring.cloud.bus.id=${spring.application.name}:${server.port}
management.endpoints.web.exposure.include=busrefresh,health,gateway,mappings
management.endpoint.gateway.access=read-only
